# Generated by Django 2.1.5 on 2019-02-12 12:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='logradouro')),
                ('number', models.CharField(max_length=100, verbose_name='número')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='bairro')),
                ('city', models.CharField(max_length=100, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('zipcode', models.CharField(max_length=100, verbose_name='CEP')),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='coordenadas')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
    ]
