# Generated by Django 2.1.5 on 2019-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPointsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Ponto geométrico',
                'verbose_name_plural': 'Pontos geométricos',
            },
        ),
    ]
