# Generated by Django 2.1.5 on 2019-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_geopointstext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='number',
            field=models.CharField(max_length=100, null=True, verbose_name='número'),
        ),
    ]
