# Generated by Django 2.1.5 on 2019-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20190216_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='logradouro'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='neighborhood',
            field=models.CharField(max_length=100, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zipcode',
            field=models.CharField(max_length=100, null=True, verbose_name='CEP'),
        ),
    ]
