# Generated by Django 2.1.5 on 2019-02-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20190216_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address2',
        ),
    ]
