# Generated by Django 2.1.5 on 2019-02-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_useraddress_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='País'),
        ),
    ]
